#!/usr/bin/env python3
"""Read text from stdin (or files) and emit a styled HTML page.

Usage:
    some_command | stdin2html.py > page.html
    some_command | stdin2html.py --title "My Report" -o page.html
    stdin2html.py file1.txt file2.txt -o report.html
"""

import argparse
import html
import os
import sys
from datetime import datetime


_BASE_STYLES = """
  :root {
    color-scheme: light dark;
    --bg: #f5f6fa;
    --fg: #1f2330;
    --card-bg: #ffffff;
    --card-border: #d8dbe4;
    --muted: #6b7280;
    --accent: #2c5fd6;
    --tab-active-bg: #ffffff;
    --tab-inactive-bg: #e8eaf0;
    --tab-hover-bg: #dde0ea;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #14161c;
      --fg: #e6e8ef;
      --card-bg: #1e2128;
      --card-border: #2c3038;
      --muted: #9aa0ad;
      --accent: #6ea0ff;
      --tab-active-bg: #1e2128;
      --tab-inactive-bg: #14161c;
      --tab-hover-bg: #22252e;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-start;
    padding: 2rem 1rem;
    background: var(--bg);
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif;
  }
  header {
    width: 100%;
    max-width: 960px;
    margin-bottom: 1.25rem;
    text-align: center;
  }
  header h1 {
    margin: 0 0 0.25rem;
    font-size: 1.75rem;
    color: var(--accent);
  }
  header .meta {
    color: var(--muted);
    font-size: 0.9rem;
  }
  pre {
    margin: 0;
    white-space: pre-wrap;
    word-break: break-word;
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
                 "Liberation Mono", monospace;
    font-size: 0.95rem;
    line-height: 1.45;
  }
  footer {
    margin-top: 1.25rem;
    color: var(--muted);
    font-size: 0.8rem;
  }
"""

STDIN_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">{refresh_tag}
<title>{title}</title>
<style>
{base_styles}
  main {{
    width: 100%;
    max-width: 960px;
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 10px;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
    padding: 1.5rem;
  }}
</style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <div class="meta">Last updated: {timestamp}</div>
  </header>
  <main>
    <pre>{content}</pre>
  </main>
  <footer>Generated by stdin2html.py</footer>
</body>
</html>
"""

TABS_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">{refresh_tag}
<title>{title}</title>
<style>
{base_styles}
  .tabbed {{
    width: 100%;
    max-width: 960px;
  }}
  .tab-nav {{
    display: flex;
    flex-wrap: wrap;
    gap: 2px;
    border-bottom: 2px solid var(--card-border);
    margin-bottom: 0;
  }}
  .tab-btn {{
    background: var(--tab-inactive-bg);
    border: 1px solid var(--card-border);
    border-bottom: none;
    border-radius: 6px 6px 0 0;
    color: var(--muted);
    cursor: pointer;
    font-size: 0.875rem;
    padding: 0.45rem 1rem;
    transition: background 0.15s, color 0.15s;
  }}
  .tab-btn:hover {{
    background: var(--tab-hover-bg);
    color: var(--fg);
  }}
  .tab-btn.active {{
    background: var(--tab-active-bg);
    border-bottom: 2px solid var(--tab-active-bg);
    color: var(--accent);
    font-weight: 600;
    margin-bottom: -2px;
  }}
  .tab-panel {{
    display: none;
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-top: none;
    border-radius: 0 0 10px 10px;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
    padding: 1.5rem;
  }}
  .tab-panel.active {{
    display: block;
  }}
</style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <div class="meta">Last updated: {timestamp}</div>
  </header>
  <div class="tabbed">
    <div class="tab-nav">
{tab_buttons}
    </div>
{tab_panels}
  </div>
  <footer>Generated by stdin2html.py</footer>
  <script>
    function showTab(idx) {{
      document.querySelectorAll('.tab-btn').forEach((b, i) => b.classList.toggle('active', i === idx));
      document.querySelectorAll('.tab-panel').forEach((p, i) => p.classList.toggle('active', i === idx));
    }}
  </script>
</body>
</html>
"""


def _render_tabs(title: str, timestamp: str, refresh_tag: str,
                 tabs: list[tuple[str, str]]) -> str:
    buttons = []
    panels = []
    for i, (label, content) in enumerate(tabs):
        active = " active" if i == 0 else ""
        buttons.append(
            f'      <button class="tab-btn{active}" onclick="showTab({i})">'
            f'{html.escape(label)}</button>'
        )
        panels.append(
            f'    <div class="tab-panel{active}">\n'
            f'      <pre>{html.escape(content)}</pre>\n'
            f'    </div>'
        )
    return TABS_TEMPLATE.format(
        title=html.escape(title),
        timestamp=html.escape(timestamp),
        refresh_tag=refresh_tag,
        base_styles=_BASE_STYLES,
        tab_buttons="\n".join(buttons),
        tab_panels="\n".join(panels),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "files",
        nargs="*",
        metavar="FILE",
        help="Input files; each becomes a tab. Omit to read from stdin.",
    )
    parser.add_argument("--title", default="Status", help="Page title")
    parser.add_argument(
        "-o", "--output",
        help="Write HTML to this file (default: stdout). "
             "Writes atomically via a temp file + rename.",
    )
    parser.add_argument(
        "--time-format",
        default="%Y-%m-%d %H:%M:%S %Z",
        help="strftime format for the timestamp",
    )
    parser.add_argument(
        "--refresh",
        type=int,
        default=0,
        metavar="SECONDS",
        help="Auto-refresh the page every N seconds (default: never)",
    )
    args = parser.parse_args()

    if args.refresh < 0:
        parser.error("--refresh must be a non-negative integer")

    timestamp = datetime.now().astimezone().strftime(args.time_format)
    refresh_tag = (
        f'\n<meta http-equiv="refresh" content="{args.refresh}">'
        if args.refresh > 0
        else ""
    )

    if args.files:
        tabs = []
        for path in args.files:
            try:
                with open(path, encoding="utf-8") as f:
                    content = f.read()
            except OSError as e:
                print(f"stdin2html.py: {e}", file=sys.stderr)
                return 1
            tabs.append((os.path.basename(path), content))
        page = _render_tabs(args.title, timestamp, refresh_tag, tabs)
    else:
        body = sys.stdin.read()
        page = STDIN_TEMPLATE.format(
            title=html.escape(args.title),
            timestamp=html.escape(timestamp),
            content=html.escape(body),
            refresh_tag=refresh_tag,
            base_styles=_BASE_STYLES,
        )

    if args.output:
        tmp = f"{args.output}.tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(page)
        os.replace(tmp, args.output)
    else:
        sys.stdout.write(page)

    return 0


if __name__ == "__main__":
    sys.exit(main())
