#!/usr/bin/env python3
"""Read text from stdin and emit a styled HTML page with the content centered.

Usage:
    some_command | stdin2html.py > page.html
    some_command | stdin2html.py --title "My Report" -o page.html
"""

import argparse
import html
import os
import sys
from datetime import datetime


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">{refresh_tag}
<title>{title}</title>
<style>
  :root {{
    color-scheme: light dark;
    --bg: #f5f6fa;
    --fg: #1f2330;
    --card-bg: #ffffff;
    --card-border: #d8dbe4;
    --muted: #6b7280;
    --accent: #2c5fd6;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #14161c;
      --fg: #e6e8ef;
      --card-bg: #1e2128;
      --card-border: #2c3038;
      --muted: #9aa0ad;
      --accent: #6ea0ff;
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-start;
    padding: 2rem 1rem;
    background: var(--bg);
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif;
  }}
  header {{
    width: 100%;
    max-width: 960px;
    margin-bottom: 1.25rem;
    text-align: center;
  }}
  header h1 {{
    margin: 0 0 0.25rem;
    font-size: 1.75rem;
    color: var(--accent);
  }}
  header .meta {{
    color: var(--muted);
    font-size: 0.9rem;
  }}
  main {{
    width: 100%;
    max-width: 960px;
    background: var(--card-bg);
    border: 1px solid var(--card-border);
    border-radius: 10px;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
    padding: 1.5rem;
  }}
  pre {{
    margin: 0;
    white-space: pre-wrap;
    word-break: break-word;
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
                 "Liberation Mono", monospace;
    font-size: 0.95rem;
    line-height: 1.45;
  }}
  footer {{
    margin-top: 1.25rem;
    color: var(--muted);
    font-size: 0.8rem;
  }}
</style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <div class="meta">Last updated: {timestamp}</div>
  </header>
  <main>
    <pre>{content}</pre>
  </main>
  <footer>Generated by stdin2html.py</footer>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--title", default="Status", help="Page title")
    parser.add_argument(
        "-o", "--output",
        help="Write HTML to this file (default: stdout). "
             "Writes atomically via a temp file + rename.",
    )
    parser.add_argument(
        "--time-format",
        default="%Y-%m-%d %H:%M:%S %Z",
        help="strftime format for the timestamp",
    )
    parser.add_argument(
        "--refresh",
        type=int,
        default=0,
        metavar="SECONDS",
        help="Auto-refresh the page every N seconds (default: never)",
    )
    args = parser.parse_args()

    if args.refresh < 0:
        parser.error("--refresh must be a non-negative integer")

    body = sys.stdin.read()
    timestamp = datetime.now().astimezone().strftime(args.time_format)

    refresh_tag = (
        f'\n<meta http-equiv="refresh" content="{args.refresh}">'
        if args.refresh > 0
        else ""
    )

    page = HTML_TEMPLATE.format(
        title=html.escape(args.title),
        timestamp=html.escape(timestamp),
        content=html.escape(body),
        refresh_tag=refresh_tag,
    )

    if args.output:
        # Atomic write so a cron-driven update never serves a half-written page.
        tmp = f"{args.output}.tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(page)
        os.replace(tmp, args.output)
    else:
        sys.stdout.write(page)

    return 0


if __name__ == "__main__":
    sys.exit(main())
